# Generated by Django 4.2.2 on 2023-07-16 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Validacion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tareaasignada',
            name='asignado_a',
        ),
        migrations.RemoveField(
            model_name='tareaasignada',
            name='tarea',
        ),
        migrations.AlterModelTable(
            name='gruposusuariotareas',
            table='GruposUsuarioTareas',
        ),
        migrations.AlterModelTable(
            name='usuariotareas',
            table='UsuarioTareas',
        ),
        migrations.DeleteModel(
            name='Tarea',
        ),
        migrations.DeleteModel(
            name='TareaAsignada',
        ),
    ]
