# Generated by Django 4.2.2 on 2023-07-16 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Validacion', '0004_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariotareas',
            name='grupo',
        ),
        migrations.RemoveField(
            model_name='usuariotareas',
            name='user',
        ),
        migrations.DeleteModel(
            name='GruposUsuarioTareas',
        ),
        migrations.DeleteModel(
            name='UsuarioTareas',
        ),
    ]
